version: "3.4"
volumes:
  shared-volume:
services:
  swoole:
    container_name: "swoole"
    environment:
      REDIS_SERVER_HOST: ${REDIS_SERVER_HOST}
    build:
      context: .
      dockerfile: swoole.dockerfile
      args:
        SWOOLE_DOCKER_VERSION: ${SWOOLE_DOCKER_VERSION}
    volumes:
      - "${GITHUB_WORKSPACE}:/imi:rw"
    working_dir: /imi
    command: tail -f /dev/null

  redis:
    image: redis:6-alpine
    container_name: redis
    ports:
      - 6379:6379
